import { Property, UserProfile, Inquiry, ChatMessage } from './types';

export const INITIAL_RENTER_PROFILE: UserProfile = {
  id: 'renter_1',
  name: 'Rohan Sharma',
  email: 'rohan.sharma@example.com',
  phone: '+91 98765 43210',
  role: 'renter',
  verificationStatus: {
    email: true,
    phone: true,
    id: true,
    income: true,
  },
  preferences: {
    budget: 25000,
    pets: true,
    nonVeg: true,
    smoking: false,
    sleepHours: 'Standard (11 PM - 7 AM)',
    roommateCount: 2,
    officeLocation: 'Indiranagar, Bangalore',
    cleanLevel: 'High',
    hobbies: ['Cooking', 'Gaming', 'Fitness', 'Reading'],
  },
  trustScore: 92,
  avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
};

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop_1',
    ownerId: 'owner_1',
    title: 'Minimalist Furnished Master Bedroom near Metropoint',
    description: 'Looking for a clean, respectful roommate to take over a fully furnished spacious master suite. It comes with a high-quality queen bed, study desk, ergonomic chair, and massive modular sliding wardrobe. Cozy living room access with smart TV and completely set up kitchen (refrigerator, cooking stove, gas, water purifier and microwave included). Located in a gated society with 24/7 security & water supply, just 5 minutes walk from the central Metro Station.',
    propertyType: 'Room',
    furnishingType: 'Furnished',
    location: 'Indiranagar, Bangalore',
    latitude: 12.9716,
    longitude: 77.6412,
    areaSqft: 350,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Microwave', 'Water Purifier', 'CCTV Security'],
    houseRules: {
      nonVegcooking: true,
      smoking: false,
      pets: true,
      couplesSelection: true,
      quietHours: '10:00 PM - 07:00 AM',
      maxOccupants: 1,
    },
    pricePerMonth: 18500,
    securityDeposit: 35000,
    availableFromDate: '2026-06-01',
    maxOccupants: 1,
    parking: 'Bike Only',
    petFriendly: true,
    photos: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'Active',
    ownerName: 'Manish Prasad',
    ownerRating: 4.8,
    ownerReviewsCount: 12,
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    views: 432,
    inquiriesCount: 15,
    allowedOccupants: 'Boys',
    roomCategory: 'Co-Living',
    featured: true,
    bathroomPhoto: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    panoramicPhoto: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&auto=format&fit=crop&q=80',
    reviewsList: [
      {
        id: 'rev_1_1',
        renterName: 'Sumit Malhotra',
        renterAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Sumit is highly supportive, respects privacy, and provides instantaneous fixes for issues. Awesome behavior!',
        roomConditionRating: 5,
        roomConditionComment: 'The ventilation and premium lights are in excellent setup condition. Well-painted walls.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-05-15'
      },
      {
        id: 'rev_1_2',
        renterName: 'Rohan Sharma',
        renterAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
        rating: 4,
        landlordCharacterRating: 4,
        landlordCharacterComment: 'Great cooperative landlord. Explains house rules clearly. Reimburses small repairs fast.',
        roomConditionRating: 4,
        roomConditionComment: 'Very clean upon arrival. Bed mattress is extremely cozy and memory-foam based.',
        bathroomHygieneRating: 4,
        reviewDate: '2025-12-08'
      }
    ]
  },
  {
    id: 'prop_2',
    ownerId: 'owner_2',
    title: 'Sun-drenched Cozy Twin Room in Luxury 2BHK Space',
    description: 'Beautiful warm room overlooking a lush green park in a quiet residential alley. Comes with beautiful natural ventilation, double bed, custom shelves, and dedicated desk space. Shared area features an elegant minimalist lounge and top-tier amenities. Zero brokerage direct deal, seeking neat occupants. Easy commutes to EPIP Zone and local startup office hubs.',
    propertyType: 'Shared Room',
    furnishingType: 'Semi-Furnished',
    location: 'Koramangala, Bangalore',
    latitude: 12.9352,
    longitude: 77.6244,
    areaSqft: 280,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Water Purifier', 'Kitchen Amenities', 'Elevator', 'Security Guard'],
    houseRules: {
      nonVegcooking: true,
      smoking: false,
      pets: false,
      couplesSelection: false,
      quietHours: '11:00 PM - 06:00 AM',
      maxOccupants: 2,
    },
    pricePerMonth: 12000,
    securityDeposit: 20000,
    availableFromDate: '2026-05-25',
    maxOccupants: 2,
    parking: 'Car & Bike',
    petFriendly: false,
    photos: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'Active',
    ownerName: 'Priyamvada Sen',
    ownerRating: 4.9,
    ownerReviewsCount: 8,
    ownerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    views: 289,
    inquiriesCount: 9,
    allowedOccupants: 'Girls',
    roomCategory: 'PG',
    bathroomPhoto: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&auto=format&fit=crop&q=80',
    panoramicPhoto: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1600&auto=format&fit=crop&q=80',
    reviewsList: [
      {
        id: 'rev_2_1',
        renterName: 'Sneha Murthy',
        renterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Priyamvada is an absolute gem. Very gentle and offers home-cooked meals during festivals. Respects safety boundaries.',
        roomConditionRating: 5,
        roomConditionComment: 'Extremely pristine and newly sanitised. Sunlight flows directly inside, very cheerful room.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-04-12'
      }
    ]
  },
  {
    id: 'prop_3',
    ownerId: 'owner_3',
    title: 'Stunning Clean Premium Studio Apartment near Tech Hub',
    description: 'Perfect for working professionals searching for independence and clean studio interiors. High ceiling design, fully self-contained kitchenette, fully modern bathroom fittings and large floor-to-ceiling balcony. Power backup and smart security with digital locks installed.',
    propertyType: 'Studio',
    furnishingType: 'Furnished',
    location: 'HSR Layout, Bangalore',
    latitude: 12.9141,
    longitude: 77.6411,
    areaSqft: 400,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Microwave', 'Gymnasium', 'Digital Lock', 'CCTV Security'],
    houseRules: {
      nonVegcooking: false,
      smoking: false,
      pets: false,
      couplesSelection: true,
      quietHours: '10:00 PM - 08:00 AM',
      maxOccupants: 2,
    },
    pricePerMonth: 24500,
    securityDeposit: 50000,
    availableFromDate: '2026-06-10',
    maxOccupants: 2,
    parking: 'Car & Bike',
    petFriendly: false,
    photos: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'Active',
    ownerName: 'Vikram Aditya',
    ownerRating: 4.6,
    ownerReviewsCount: 15,
    ownerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    views: 512,
    inquiriesCount: 22,
    allowedOccupants: 'Family',
    roomCategory: 'Flatshare',
    bathroomPhoto: 'https://images.unsplash.com/photo-1620626011161-00d4ce6503c5?w=800&auto=format&fit=crop&q=80',
    panoramicPhoto: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1600&auto=format&fit=crop&q=80',
    reviewsList: [
      {
        id: 'rev_3_1',
        renterName: 'Abhishek Roy',
        renterAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
        rating: 4,
        landlordCharacterRating: 4,
        landlordCharacterComment: 'Practical and behaves like a thorough professional. Clear documentation and automated rent invoicing system.',
        roomConditionRating: 4,
        roomConditionComment: 'Highly modern bathroom with flawless plumbing. Kitchen tools are excellent.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-03-01'
      }
    ]
  },
  {
    id: 'prop_4',
    ownerId: 'owner_4',
    title: 'Chic Flatshare Room with Skyline View in Bandra West',
    description: 'Enjoy true Mumbai sea-side vibe in this high-rise 3BHK flatshare. Private ensuite room with wooden flooring, massive windows overlooking the Bandra coastline. Excellent connectivity, surrounded by iconic cafes. Living room has beanbags, game consoles, and a welcoming co-living community of young creative startups.',
    propertyType: 'Room',
    furnishingType: 'Furnished',
    location: 'Bandra West, Mumbai',
    latitude: 19.0596,
    longitude: 72.8295,
    areaSqft: 320,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'CCTV Security', 'Elevator', 'Gymnasium'],
    houseRules: {
      nonVegcooking: true,
      smoking: true,
      pets: false,
      couplesSelection: true,
      quietHours: '11:00 PM - 08:00 AM',
      maxOccupants: 1,
    },
    pricePerMonth: 38000,
    securityDeposit: 80000,
    availableFromDate: '2026-06-05',
    maxOccupants: 1,
    parking: 'No',
    petFriendly: false,
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'Active',
    ownerName: 'Ayush Mehra',
    ownerRating: 4.7,
    ownerReviewsCount: 18,
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    views: 640,
    inquiriesCount: 31,
    allowedOccupants: 'Boys',
    roomCategory: 'Flatshare',
    bathroomPhoto: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    panoramicPhoto: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1600&auto=format&fit=crop&q=80',
    reviewsList: [
      {
        id: 'rev_4_1',
        renterName: 'Ravi Verma',
        renterAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Ayush is incredibly cool. Occasional gamer himself, chilled out with friends visiting, and behaves like an equal peer.',
        roomConditionRating: 4,
        roomConditionComment: 'Incredible wooden panels. Beautiful window set up.',
        bathroomHygieneRating: 4,
        reviewDate: '2026-04-10'
      }
    ]
  },
  {
    id: 'prop_5',
    ownerId: 'owner_5',
    title: 'Peaceful Spacious Co-living Unit in Premium Golf Course Road Close-knit Community',
    description: 'Looking for friendly corporate roommates for a luxury duplex in Sector 54. Private detached room with attached modern washroom and smart layout. Extremely premium finishing, spacious balcony space overlooking the park. Walking distance to Sector 54 Rapid Metro Station.',
    propertyType: 'Shared Room',
    furnishingType: 'Furnished',
    location: 'Golf Course Road, Gurgaon',
    latitude: 28.4282,
    longitude: 77.1006,
    areaSqft: 450,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Microwave', 'Security Guard', 'Elevator', 'Water Purifier'],
    houseRules: {
      nonVegcooking: true,
      smoking: false,
      pets: true,
      couplesSelection: false,
      quietHours: '10:00 PM - 07:00 AM',
      maxOccupants: 2,
    },
    pricePerMonth: 21000,
    securityDeposit: 40000,
    availableFromDate: '2026-06-01',
    maxOccupants: 2,
    parking: 'Car & Bike',
    petFriendly: true,
    photos: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'Active',
    ownerName: 'Siddharth Singhal',
    ownerRating: 4.5,
    ownerReviewsCount: 5,
    ownerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    views: 180,
    inquiriesCount: 7,
    allowedOccupants: 'Girls',
    roomCategory: 'PG',
    bathroomPhoto: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&auto=format&fit=crop&q=80',
    panoramicPhoto: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1600&auto=format&fit=crop&q=80',
    reviewsList: [
      {
        id: 'rev_5_1',
        renterName: 'Riya Singhi',
        renterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
        rating: 4,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Siddharth is highly respectful. He treats and coordinates everything with maximum professional composure.',
        roomConditionRating: 4,
        roomConditionComment: 'The shared living room space has gorgeous high key lights. Premium building lobby.',
        bathroomHygieneRating: 4,
        reviewDate: '2026-02-15'
      }
    ]
  },
  {
    id: 'prop_6',
    ownerId: 'owner_6',
    title: 'Vintage High-Ceiling Studio Apartment near Connaught Place',
    description: 'Beautifully designed authentic colonial-era studio with high arched ceilings and contemporary retro design. Furnished with premium solid teak wood furniture, custom rugs, and warm yellow lighting. Features completely self-contained modular pantry, instant washer-dryer, dual smart workspace desks, and digital security locks. Situated in an upscale safe green alley in Central Delhi.',
    propertyType: 'Studio',
    furnishingType: 'Furnished',
    location: 'Connaught Place, Delhi',
    latitude: 28.6304,
    longitude: 77.2177,
    areaSqft: 500,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Microwave', 'Water Purifier', 'CCTV Security', 'Digital Lock'],
    houseRules: {
      nonVegcooking: false,
      smoking: false,
      pets: false,
      couplesSelection: true,
      quietHours: '11:00 PM - 08:00 AM',
      maxOccupants: 2,
    },
    pricePerMonth: 29500,
    securityDeposit: 60000,
    availableFromDate: '2026-06-15',
    maxOccupants: 2,
    parking: 'Car & Bike',
    petFriendly: false,
    photos: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'Active',
    ownerName: 'Kabir Thapar',
    ownerRating: 4.9,
    ownerReviewsCount: 22,
    ownerAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    views: 890,
    inquiriesCount: 45,
    allowedOccupants: 'Any',
    roomCategory: 'PG',
    bathroomPhoto: 'https://images.unsplash.com/photo-1620626011161-00d4ce6503c5?w=800&auto=format&fit=crop&q=80',
    panoramicPhoto: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1600&auto=format&fit=crop&q=80',
    reviewsList: [
      {
        id: 'rev_6_1',
        renterName: 'Dhruv Dixit',
        renterAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Kabir Thapar is a gentleman. Always available over WhatsApp, doesn\'t disturb our study timings, and organized a welcome party.',
        roomConditionRating: 5,
        roomConditionComment: 'The high ceiling keeps it incredibly cool even in peak summer. Authentic aesthetic.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-05-01'
      }
    ]
  },
  {
    id: 'prop_7',
    ownerId: 'owner_7',
    title: 'Cozy Furnished Room for Students near LNCT & BHEL',
    description: 'Perfect for students and working professionals. Located in the bustling heart of Indrapuri Sector C, with super easy campus connectivity to LNCT college, coaching institutes, and BHEL. Comes with a sturdy wooden bed, study table, large window for airy natural ventilation, and standard storage wardrobe. House has a small common lobby, purified water, refrigerator, and robust security. Typical Indian home warmth guaranteed!',
    propertyType: 'Room',
    furnishingType: 'Furnished',
    location: 'Indrapuri, Bhopal',
    latitude: 23.2625,
    longitude: 77.4645,
    areaSqft: 200,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Water Purifier', 'CCTV Security'],
    houseRules: {
      nonVegcooking: false,
      smoking: false,
      pets: false,
      couplesSelection: false,
      quietHours: '10:00 PM - 06:00 AM',
      maxOccupants: 1,
    },
    pricePerMonth: 6500,
    securityDeposit: 10000,
    availableFromDate: '2026-06-01',
    maxOccupants: 1,
    parking: 'Bike Only',
    petFriendly: false,
    photos: [
      '/src/assets/images/indrapuri_room_1779355766119.png'
    ],
    status: 'Active',
    ownerName: 'Rajesh Kumar',
    ownerRating: 4.7,
    ownerReviewsCount: 9,
    ownerAvatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=200&auto=format&fit=crop&q=80',
    views: 145,
    inquiriesCount: 4,
    allowedOccupants: 'Boys',
    roomCategory: 'Co-Living',
    featured: true,
    bathroomPhoto: '/src/assets/images/bhopal_washroom_1_1779355838260.png',
    reviewsList: [
      {
        id: 'rev_7_1',
        renterName: 'Shubham Patel',
        renterAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Rajesh Uncle is extremely helpful. He lives on the floor below and is always ready to guide about local transport, tiffin services, and general safety.',
        roomConditionRating: 5,
        roomConditionComment: 'The room feels incredibly safe and airy. Excellent window grill setup.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-05-10'
      }
    ]
  },
  {
    id: 'prop_8',
    ownerId: 'owner_8',
    title: 'Premium Executive Studio near DB City Mall',
    description: 'Looking for a sophisticated and clean living space? This studio in Zone-1, MP Nagar is perfect for IT professionals and corporate managers. Fully furnished with high-end premium modern single bed with elegant white support linen, customized sleek desk, high speed internet router, and sleek cabinets. Direct road access, adjacent to premier corporate offices, banks, and great fine-dining spots. Unmatched premium city center experience with clean services.',
    propertyType: 'Studio',
    furnishingType: 'Furnished',
    location: 'MP Nagar, Bhopal',
    latitude: 23.2312,
    longitude: 77.4323,
    areaSqft: 350,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Refrigerator', 'Geyser', 'Water Purifier', 'CCTV Security', 'Elevator', 'Gymnasium'],
    houseRules: {
      nonVegcooking: true,
      smoking: false,
      pets: false,
      couplesSelection: true,
      quietHours: '11:00 PM - 07:00 AM',
      maxOccupants: 1,
    },
    pricePerMonth: 12500,
    securityDeposit: 25000,
    availableFromDate: '2026-05-28',
    maxOccupants: 1,
    parking: 'Car & Bike',
    petFriendly: false,
    photos: [
      '/src/assets/images/mp_nagar_room_1779355784293.png'
    ],
    status: 'Active',
    ownerName: 'Suresh Gupta',
    ownerRating: 4.8,
    ownerReviewsCount: 14,
    ownerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    views: 320,
    inquiriesCount: 11,
    allowedOccupants: 'Any',
    roomCategory: 'Co-Living',
    featured: true,
    bathroomPhoto: '/src/assets/images/bhopal_washroom_2_1779355857095.png',
    reviewsList: [
      {
        id: 'rev_8_1',
        renterName: 'Aarav Nair',
        renterAvatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Gupta ji is highly professional. The lease terms and receipt management are managed thoroughly via WhatsApp. Clear experience!',
        roomConditionRating: 4,
        roomConditionComment: 'Highly state-of-the-art building layout with efficient geyser and pristine commode.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-04-20'
      }
    ]
  },
  {
    id: 'prop_9',
    ownerId: 'owner_9',
    title: 'Charming Compact Private Room with Greenery views',
    description: 'Cozy and extremely affordable standard single room in Ratnagiri. Located in a family-oriented green residential society with high privacy. Clean single bed setup with nice Orange block print textiles, proper cross ventilation, clean bathroom access, and standard home cooling fan. Perfect alternative to expensive PGs, offering cozy homely food delivery options nearby.',
    propertyType: 'Room',
    furnishingType: 'Semi-Furnished',
    location: 'Ratnagiri, Bhopal',
    latitude: 23.2721,
    longitude: 77.4812,
    areaSqft: 180,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'High Speed WiFi', 'Refrigerator', 'Geyser', 'Water Purifier'],
    houseRules: {
      nonVegcooking: false,
      smoking: false,
      pets: false,
      couplesSelection: false,
      quietHours: '10:00 PM - 06:00 AM',
      maxOccupants: 1,
    },
    pricePerMonth: 5000,
    securityDeposit: 8000,
    availableFromDate: '2026-06-01',
    maxOccupants: 1,
    parking: 'Bike Only',
    petFriendly: false,
    photos: [
      '/src/assets/images/ratnagiri_room_1779355799560.png'
    ],
    status: 'Active',
    ownerName: 'Anoop Saxena',
    ownerRating: 4.6,
    ownerReviewsCount: 3,
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    views: 89,
    inquiriesCount: 2,
    allowedOccupants: 'Boys',
    roomCategory: 'PG',
    featured: true,
    bathroomPhoto: '/src/assets/images/bhopal_washroom_1_1779355838260.png',
    reviewsList: [
      {
        id: 'rev_9_1',
        renterName: 'Rishabh Tiwari',
        renterAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
        rating: 4,
        landlordCharacterRating: 4,
        landlordCharacterComment: 'Anoop ji keeps the atmosphere peaceful and cozy. Zero issues with visitors during daytime.',
        roomConditionRating: 4,
        roomConditionComment: 'Extremely good value for PG students, the bed print is typical Indian home style and super comfortable.',
        bathroomHygieneRating: 4,
        reviewDate: '2026-05-12'
      }
    ]
  },
  {
    id: 'prop_10',
    ownerId: 'owner_10',
    title: 'Modern High-speed WiFi Co-living Flatshare Room',
    description: 'Looking to live in a highly neat co-living bubble? This flatshare room in Ayodhya Extension stands out beautifully. Sleek cream white layout, cute contemporary books shelf, neat single bed setup with stylish blue covers, and state-of-the-art washroom amenities. Perfect match score for millennials looking for zero-brokerage safe co-living spaces.',
    propertyType: 'Shared Room',
    furnishingType: 'Furnished',
    location: 'Ayodhya Extension, Bhopal',
    latitude: 23.2845,
    longitude: 77.4611,
    areaSqft: 220,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Water Purifier', 'CCTV Security'],
    houseRules: {
      nonVegcooking: true,
      smoking: false,
      pets: true,
      couplesSelection: true,
      quietHours: '11:00 PM - 07:00 AM',
      maxOccupants: 2,
    },
    pricePerMonth: 8000,
    securityDeposit: 15000,
    availableFromDate: '2026-05-25',
    maxOccupants: 2,
    parking: 'Car & Bike',
    petFriendly: true,
    photos: [
      '/src/assets/images/ayodhya_room_1779355819273.png'
    ],
    status: 'Active',
    ownerName: 'Deepak Sharma',
    ownerRating: 4.9,
    ownerReviewsCount: 16,
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    views: 240,
    inquiriesCount: 8,
    allowedOccupants: 'Any',
    roomCategory: 'Flatshare',
    featured: true,
    bathroomPhoto: '/src/assets/images/bhopal_washroom_2_1779355857095.png',
    reviewsList: [
      {
        id: 'rev_10_1',
        renterName: 'Karan Mehra',
        renterAvatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Sharma is very communicative and behaves like a flatmate. Fully modern thinking, great peer.',
        roomConditionRating: 5,
        roomConditionComment: 'The blue theme and marble flooring look absolutely clean and neat.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-05-18'
      }
    ]
  },
  {
    id: 'prop_11',
    ownerId: 'owner_11',
    title: 'Upscale Sun-kissed Private Suite in Arera Colony',
    description: 'A premium, highly secure top-floor room in the serene residential streets of E-7, Arera Colony. Ideal for executive officers or doctors. It has elegant solid teak wood finish single bed with orthopedic mattress, dedicated reading desk overlooking a private balcony full of plants, sliding glass entry, and spacious built-in solid cedar wooden wardrobe. Access to a completely functional modern kitchen, water purifier, high-pressure geyser, and standard parking.',
    propertyType: 'Room',
    furnishingType: 'Furnished',
    location: 'Arera Colony, Bhopal',
    latitude: 23.2125,
    longitude: 77.4255,
    areaSqft: 280,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Power Backup', 'Air Conditioning', 'High Speed WiFi', 'Washing Machine', 'Refrigerator', 'Geyser', 'Water Purifier', 'CCTV Security'],
    houseRules: {
      nonVegcooking: false,
      smoking: false,
      pets: false,
      couplesSelection: false,
      quietHours: '10:00 PM - 06:00 AM',
      maxOccupants: 1,
    },
    pricePerMonth: 12000,
    securityDeposit: 20000,
    availableFromDate: '2026-06-01',
    maxOccupants: 1,
    parking: 'Car & Bike',
    petFriendly: false,
    photos: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'Active',
    ownerName: 'Dr. Alok Verma',
    ownerRating: 4.9,
    ownerReviewsCount: 5,
    ownerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    views: 198,
    inquiriesCount: 3,
    allowedOccupants: 'Any',
    roomCategory: 'Co-Living',
    featured: true,
    bathroomPhoto: '/src/assets/images/bhopal_washroom_2_1779355857095.png',
    reviewsList: [
      {
        id: 'rev_11_1',
        renterName: 'Nikhil Saxena',
        renterAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
        rating: 5,
        landlordCharacterRating: 5,
        landlordCharacterComment: 'Dr. Verma treats renters with absolute dignity and respect. The compound is extremely secure, clean, and silent. Unbeatable location in Arera Colony!',
        roomConditionRating: 5,
        roomConditionComment: 'Pristine tiles and incredibly cozy private balcony views of palm trees.',
        bathroomHygieneRating: 5,
        reviewDate: '2026-05-15'
      }
    ]
  }
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'inq_1',
    propertyId: 'prop_1',
    renterId: 'renter_1',
    renterName: 'Rohan Sharma',
    renterAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    renterEmail: 'rohan.sharma@example.com',
    renterPhone: '+91 98765 43210',
    status: 'Pending',
    matchScore: 94,
    trustScore: 92,
    applicationDate: '2026-05-18',
    moveInDate: '2026-06-01',
    leaseDuration: '11 Months',
    preferences: INITIAL_RENTER_PROFILE.preferences,
  },
  {
    id: 'inq_2',
    propertyId: 'prop_2',
    renterId: 'renter_2',
    renterName: 'Priya Iyer',
    renterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    renterEmail: 'priya.iyer@example.com',
    renterPhone: '+91 87654 32109',
    status: 'Accepted',
    matchScore: 78,
    trustScore: 88,
    applicationDate: '2026-05-15',
    moveInDate: '2026-05-28',
    leaseDuration: '6 Months',
    preferences: {
      budget: 15000,
      pets: false,
      nonVeg: true,
      smoking: false,
      sleepHours: 'Early Bird (9 PM - 5 AM)',
      roommateCount: 1,
      officeLocation: 'Koramangala, Bangalore',
      cleanLevel: 'High',
      hobbies: ['Yoga', 'Pottery', 'Cooking'],
    },
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_1',
    senderId: 'renter_1',
    receiverId: 'owner_1',
    propertyId: 'prop_1',
    text: "Hello! Responding to your listing near Metropoint. I am really interested in the double furnished master suite.",
    timestamp: '2026-05-18T10:30:00Z',
    isRead: true,
  },
  {
    id: 'msg_2',
    senderId: 'owner_1',
    receiverId: 'renter_1',
    propertyId: 'prop_1',
    text: "Hi Rohan! Thanks for reaching out. The room is available for visits. Do you want to check compatibility with our AI engine first?",
    timestamp: '2026-05-18T10:35:00Z',
    isRead: true,
  },
  {
    id: 'msg_3',
    senderId: 'renter_1',
    receiverId: 'owner_1',
    propertyId: 'prop_1',
    text: "Yes, I ran the Matching analyzer and we scored 94%! Our rules match perfectly and I pet-love dogs.",
    timestamp: '2026-05-18T10:38:00Z',
    isRead: false,
  }
];
